create table studio
(
    id   bigint generated by default as identity,
    name character varying
);

create table producer
(
    id           bigint generated by default as identity,
    fist_name    character varying,
    middle_names character varying,
    last_name    character varying
);