create table studio
(
    id   bigint generated by default as identity,
    name character varying
);

create table producer
(
    id          bigint generated by default as identity,
    fistName    character varying,
    middleNames character varying,
    lastName    character varying
);